name = "stock-stocktradingappwithaiassistant"
compatibility_date = "2024-01-05"
workers_dev = true
main = "./worker.js"

[build]
command = "npm run build"
watch_dir = "build_output"

[site]
bucket = "./build_output"
pages_build_output_dir = "build_output"

[build.upload]
format = "modules"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[triggers]
crons = []

# Development environment
[env.development]
workers_dev = true

[env.development.vars]
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ENABLE_CORS = "true"
STREAMLIT_SERVER_ENABLE_HTTPS = "true"

# Production environment
[env.production]
workers_dev = true

[env.production.vars]
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ENABLE_CORS = "true"
STREAMLIT_SERVER_ENABLE_HTTPS = "true"

[[env.production.routes]]
pattern = "stock-stocktradingappwithaiassistant.pages.dev/*"
zone_name = "pages.dev"

# SSL/TLS Configuration
[ssl]
certificate_file = ""  # Leave empty for Cloudflare-managed certificates
private_key_file = ""  # Leave empty for Cloudflare-managed certificates
always_use_https = true
