name = "stock-stocktradingappwithaiassistant"
compatibility_date = "2024-01-05"
workers_dev = true
main = "./worker.js"

[build]
command = "npm run build"
watch_dir = "build_output"

[site]
bucket = "./build_output"

[build.upload]
format = "modules"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[triggers]
crons = []

# Development environment
[env.development]
workers_dev = true
vars = { STREAMLIT_SERVER_PORT = "8501" }

# Production environment
[env.production]
workers_dev = true
vars = { STREAMLIT_SERVER_PORT = "8501" }
routes = [
  { pattern = "stock-stocktradingappwithaiassistant.pages.dev/*", zone_name = "pages.dev" }
]
