[server]
port = 8501
address = "0.0.0.0"
headless = true
baseUrlPath = "_app"
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
runOnSave = true

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8501

[theme]
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#DCDCDC"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false
showfileUploaderEncoding = false

[global]
developmentMode = false
showWarningOnDirectExecution = false

[mapbox]
token = ""
