[server]
port = 8501
address = "0.0.0.0"
headless = true
baseUrlPath = "_app"
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
gatherUsageStats = false

[theme]
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#DCDCDC"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false
showfileUploaderEncoding = false

[global]
developmentMode = false
showWarningOnDirectExecution = true
