[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[logger]
level = "error"
