[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
runOnSave = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false

[global]
developmentMode = false
showWarningOnDirectExecution = false

[mapbox]
token = ""

[runner]
magicEnabled = true
installTracker = true

[client]
showErrorDetails = true
toolbarMode = "auto"
