[server]
port = 8501
address = "0.0.0.0"
maxUploadSize = 200
enableCORS = true
enableXsrfProtection = false  # Temporarily disable for debugging
baseUrlPath = ""
allowIframingFrom = ["*"]  # Allow embedding from any domain
headless = true
runOnSave = true

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8501

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false

[global]
developmentMode = true
showWarningOnDirectExecution = false

[mapbox]
token = ""

[runner]
magicEnabled = true
installTracker = true

[client]
showErrorDetails = true
toolbarMode = "auto"
caching = true
